server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true&useSSl=false
    username: root
    password: 123456

mybatis:
  mapperLocation: classpath:mapper/*.xml
  type-aliases-package: com.simulation.springcould.entities